server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/members/**

        - id: policy-service
          uri: lb://policy-service
          predicates:
            - Path=/api/policies/**

        - id: claim-service
          uri: lb://claim-service
          predicates:
            - Path=/api/claims/**

        # Rutas para documentación OpenAPI de cada servicio
        - id: member-service-docs
          uri: lb://member-service
          predicates:
            - Path=/api/members/v3/api-docs
          filters:
            - RewritePath=/api/members/v3/api-docs, /v3/api-docs

        - id: policy-service-docs
          uri: lb://policy-service
          predicates:
            - Path=/api/policies/v3/api-docs
          filters:
            - RewritePath=/api/policies/v3/api-docs, /v3/api-docs

        - id: claim-service-docs
          uri: lb://claim-service
          predicates:
            - Path=/api/claims/v3/api-docs
          filters:
            - RewritePath=/api/claims/v3/api-docs, /v3/api-docs

        - id: auth-service-docs
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/v3/api-docs
          filters:
            - RewritePath=/api/auth/v3/api-docs, /v3/api-docs
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/insurance-service/protocol/openid-connect/certs

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Member Service
        url: /api/members/v3/api-docs
      - name: Policy Service
        url: /api/policies/v3/api-docs
      - name: Claim Service
        url: /api/claims/v3/api-docs
      - name: Auth Service
        url: /api/auth/v3/api-docs
    enabled: true
  api-docs:
    enabled: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: false
    hostname: ${HOSTNAME:api-gateway}
    non-secure-port: ${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route: DEBUG
    reactor.netty.http.client: DEBUG
