server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/members/**

        - id: policy-service
          uri: lb://policy-service
          predicates:
            - Path=/api/policies/**

        - id: claim-service
          uri: lb://claim-service
          predicates:
            - Path=/api/claims/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/inscurance-service-microservice
          jwk-set-uri: http://keycloak:8080/realms/inscurance-service-microservice/protocol/openid-connect/certs

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: false
    hostname: ${HOSTNAME:api-gateway}
    non-secure-port: ${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route: DEBUG
    reactor.netty.http.client: DEBUG
