server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/insurance_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: false
    hostname: ${HOSTNAME:claim-service}
    non-secure-port: ${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

document:
  service:
    url: http://localhost:8085/api/documents
    timeout: 30000 # 30 segundos
    max-in-memory-size: 16777216 # 16MB
