server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/insurance_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: false
    hostname: ${HOSTNAME:member-service}
    non-secure-port: ${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

aws:
  region:
    static: ${AWS_REGION:us-east-1}
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID:test}
    secret-key: ${AWS_SECRET_ACCESS_KEY:test}
  s3:
    endpoint: ${AWS_S3_ENDPOINT:http://localhost:4566}
    bucket: ${AWS_S3_BUCKET_NAME:insurance-documents}
  path-style-access-enabled: true
  stack:
    auto: false
