server:
  port: 8085

spring:
  autoconfigure:
    exclude:
      - org.springframework.ai.retry.autoconfigure.SpringAiRetryAutoConfiguration
  datasource:
    url: jdbc:postgresql://postgres:5432/insurance_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      api-key: ${OPENAI_API_KEY} # Variable de entorno
      timeout-seconds: 30
      model: gpt-4.1-mini
      temperature: 0.2
      max-tokens: 2048
      retries: 3
    model:
      chat:
        # Habilita el cliente de Vertex AI (activado por defecto) [1, 2]
        enabled: vertexai
    vertex:
      ai:
        gemini:
          api-key: ${GEMINI_API_KEY} # Variable de entorno
          # ID del proyecto en Google Cloud y región (ej. us-central1) [2, 3]
          project-id: "gen-lang-client-0104227904"
          # Opcional: Especificar transporte GRPC o REST (por defecto es GRPC) [2, 4]
          transport: GRPC
          chat:
            options:
              # Modelos disponibles: gemini-2.0-flash, gemini-2.0-flash-lite, etc. [3, 4]
              model: gemini-2.0-flash
              # Controla la aleatoriedad (0.0 a 1.0) [5, 6]
              temperature: 0.7
              # Máximo de tokens a generar [7]
              max-output-tokens: 2048
              # Configuración de respuesta: text/plain o application/json [5]
              response-mime-type: "text/plain"

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: false
    hostname: ${HOSTNAME:member-service}
    non-secure-port: ${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

aws:
  region:
    static: ${AWS_REGION:us-east-1}
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID:test}
    secret-key: ${AWS_SECRET_ACCESS_KEY:test}
  s3:
    endpoint: ${AWS_S3_ENDPOINT:http://localhost:4566}
    bucket: ${AWS_S3_BUCKET_NAME:insurance-documents}
  path-style-access-enabled: true
  stack:
    auto: false

gemini:
  ia:
    api-key: ${GEMINI_API_KEY}
    model: gemini-1.5-flash-latest
