server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/insurance_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ia:
    openai:
      api-key: ${OPENAI_API_KEY} # Variable de entorno
      base_url: https://openrouter.ai/api
      chat:
        options:
          model: google/gemini-2.0-flash-exp:free

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: false
    hostname: ${HOSTNAME:member-service}
    non-secure-port: ${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
